### ISSUE TITLE
Fix websites.txt Dependency! 

### ISSUE THREAD

**Issue by Tearever** [Tearever/ScrapingTheeWeb#2]
Since we already have code to fix the directory dependencies, we need to implement code to make sure that if websites.txt is not present, we need to then create a websites.txt file. We could either prompt the user with a message in the console to populate the file or make them go through a query of adding files.

**Comment by Brandon-7-Sharp** [comment]
My workers and I (mainly them) created a function in the test_conditions.py that checks if the websites.txt exists, and if it does not, the function will create the file and prompt the user to input weblinks into it, then re-run the program.
